leftnav:
- identifier: 4ff3236d-bb77-bc34-6022-6ad4dce64b50
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 3da02316-bd16-dd1d-d117-db2d3a5cdf73
  name: Readings
  pageRef: /pages/readings
  weight: 20
- identifier: 6d991d2d-9834-a247-946a-f6ed255c2dcf
  name: Lecture and Recitation Notes
  pageRef: /pages/lecture-and-recitation-notes
  weight: 30
- identifier: 790693dd-03fa-16d8-62fd-02407cfcb455
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 883b00d7-5d4b-ac8a-589c-8fb34101f032
  name: Unit Index
  pageRef: /pages/unit-index
  weight: 50
- identifier: bebdc8ab-5b1f-9682-d6b7-62b671b5cf25
  name: 'Unit 1: An Introduction to Analytics'
  pageRef: /pages/an-introduction-to-analytics/
  weight: 60
- identifier: c846ced6-fc6d-3bc9-64e0-47324e251a98
  name: 'Unit 2: Linear Regression'
  pageRef: /pages/linear-regression/
  weight: 70
- identifier: c4464cf4-9ddb-1a4b-c78c-faa6f93b74de
  name: 'Unit 3: Logistic Regression'
  pageRef: /pages/logistic-regression/
  weight: 80
- identifier: 19c8cf92-e31d-034a-1ea1-5ad53194d892
  name: 'Unit 4: Trees'
  pageRef: /pages/trees/
  weight: 90
- identifier: 5847ad87-9afe-cf3e-9b93-c20cffe87acf
  name: 'Unit 5: Text Analytics'
  pageRef: /pages/text-analytics/
  weight: 100
- identifier: 6e343503-94a0-f948-51f4-8f324b5f657f
  name: 'Unit 6: Clustering'
  pageRef: /pages/clustering/
  weight: 110
- identifier: ab87d151-cf8c-fe95-c873-e816df164d38
  name: 'Unit 7: Visualization'
  pageRef: /pages/visualization/
  weight: 120
- identifier: daafaa58-867c-9765-f1c4-c60a9c0ed426
  name: 'Unit 8: Linear Optimization'
  pageRef: /pages/linear-optimization/
  weight: 130
- identifier: db42b40a-d705-f431-a7e2-3a1d11cec341
  name: 'Unit 9: Integer Optimization'
  pageRef: /pages/integer-optimization/
  weight: 140
- identifier: a958c6c3-2e8f-cfa1-cbab-a162067382a1
  name: 1.1 Welcome to Unit 1
  pageRef: /pages/an-introduction-to-analytics/welcome-to-unit-1
  parent: bebdc8ab-5b1f-9682-d6b7-62b671b5cf25
  weight: 10
- identifier: 9fb45936-9f44-df97-dad3-89bb5d1aa82c
  name: '1.2 The Analytics Edge: Intelligence, Happiness, and Health  (Lecture Sequence)'
  pageRef: /pages/an-introduction-to-analytics/the-analytics-edge-intelligence-happiness-and-health-lecture-sequence/
  parent: bebdc8ab-5b1f-9682-d6b7-62b671b5cf25
  weight: 20
- identifier: 1ac933da-13d1-3dfa-2e38-03abf2d6971f
  name: '1.3 Working with Data: An Introduction to R '
  pageRef: /pages/an-introduction-to-analytics/working-with-data-an-introduction-to-r/
  parent: bebdc8ab-5b1f-9682-d6b7-62b671b5cf25
  weight: 30
- identifier: 7ae5f9ab-ee30-803e-522b-c737bfb5e185
  name: '1.4 Understanding Food: Nutritional Education with Data  (Recitation)'
  pageRef: /pages/an-introduction-to-analytics/understanding-food-nutritional-education-with-data-recitation/
  parent: bebdc8ab-5b1f-9682-d6b7-62b671b5cf25
  weight: 40
- identifier: 0af41c2f-ca68-84fa-b36c-0a31155319b9
  name: 1.5 Assignment 1
  pageRef: /pages/an-introduction-to-analytics/assignment-1/
  parent: bebdc8ab-5b1f-9682-d6b7-62b671b5cf25
  weight: 50
- identifier: 4f0a4b24-64cb-eba3-50fe-fae41b407cd6
  name: 2.1 Welcome to Unit 2
  pageRef: /pages/linear-regression/welcome-to-unit-2
  parent: c846ced6-fc6d-3bc9-64e0-47324e251a98
  weight: 10
- identifier: 4495fb48-3934-3c33-23b2-2ef2104af559
  name: '2.2 The Statistical Sommelier: An Introduction to Linear Regression'
  pageRef: /pages/linear-regression/the-statistical-sommelier-an-introduction-to-linear-regression/
  parent: c846ced6-fc6d-3bc9-64e0-47324e251a98
  weight: 20
- identifier: fcb6a63f-4737-920a-80bf-15309d3ee7b6
  name: '2.3 Moneyball: The Power of Sports Analytics '
  pageRef: /pages/linear-regression/moneyball-the-power-of-sports-analytics/
  parent: c846ced6-fc6d-3bc9-64e0-47324e251a98
  weight: 30
- identifier: 3d4f0b49-ab63-6ab4-200c-8f27a219c0dc
  name: 2.4 Playing Moneyball in the NBA  (Recitation)
  pageRef: /pages/linear-regression/playing-moneyball-in-the-nba-recitation/
  parent: c846ced6-fc6d-3bc9-64e0-47324e251a98
  weight: 40
- identifier: d3823600-300c-0300-0e79-696e835f8f2f
  name: 2.5 Assignment 2
  pageRef: /pages/linear-regression/assignment-2/
  parent: c846ced6-fc6d-3bc9-64e0-47324e251a98
  weight: 50
- identifier: 29b6c08f-b66f-c563-5e83-256d2e175fed
  name: 3.1 Welcome to Unit 3
  pageRef: /pages/logistic-regression/welcome-to-unit-3
  parent: c4464cf4-9ddb-1a4b-c78c-faa6f93b74de
  weight: 10
- identifier: 3063320a-4175-6b8a-4fa9-892f61b52c0d
  name: '3.2 Modeling the Expert: An Introduction to Logistic Regression'
  pageRef: /pages/logistic-regression/modeling-the-expert-an-introduction-to-logistic-regression/
  parent: c4464cf4-9ddb-1a4b-c78c-faa6f93b74de
  weight: 20
- identifier: 58bb6065-48df-9c3a-8c14-8318a4e0e5c7
  name: '3.3 The Framingham Heart Study: Evaluating Risk Factors to Save Lives '
  pageRef: /pages/logistic-regression/the-framingham-heart-study-evaluating-risk-factors-to-save-lives/
  parent: c4464cf4-9ddb-1a4b-c78c-faa6f93b74de
  weight: 30
- identifier: cd55cbba-60f6-d5d3-7320-e05f520c4cf1
  name: '3.4 Election Forecasting: Predicting the Winner Before any Votes are Cast  (Recitation)'
  pageRef: /pages/logistic-regression/election-forecasting-predicting-the-winner-before-any-votes-are-cast-recitation/
  parent: c4464cf4-9ddb-1a4b-c78c-faa6f93b74de
  weight: 40
- identifier: d4a650ea-930c-2c8c-0f98-9b353a5a342e
  name: 3.5 Assignment 3
  pageRef: /pages/logistic-regression/assignment-3/
  parent: c4464cf4-9ddb-1a4b-c78c-faa6f93b74de
  weight: 50
- identifier: 1bbf68ce-76a4-7a1d-41c9-0293ba65ab6e
  name: 4.1 Welcome to Unit 4
  pageRef: /pages/trees/welcome-to-unit-4
  parent: 19c8cf92-e31d-034a-1ea1-5ad53194d892
  weight: 10
- identifier: 11f9b44d-c296-0689-414b-8c313764a18d
  name: '4.2 Judge, Jury, and Classifier: An Introduction to Trees '
  pageRef: /pages/trees/judge-jury-and-classifier-an-introduction-to-trees/
  parent: 19c8cf92-e31d-034a-1ea1-5ad53194d892
  weight: 20
- identifier: 52a221dd-c011-90a4-45b1-a393b15cb810
  name: '4.3 Keeping an Eye on Healthcare Costs: The D2Hawkeye Story '
  pageRef: /pages/trees/keeping-an-eye-on-healthcare-costs-the-d2hawkeye-story/
  parent: 19c8cf92-e31d-034a-1ea1-5ad53194d892
  weight: 30
- identifier: aef27920-c51c-efd1-88ed-937539251bd9
  name: '4.4 Location, Location, Location: Regression Trees for Housing Data  (Recitation)'
  pageRef: /pages/trees/location-location-location-regression-trees-for-housing-data-recitation/
  parent: 19c8cf92-e31d-034a-1ea1-5ad53194d892
  weight: 40
- identifier: 11ad34c8-1083-2b18-6afa-cd57f2616109
  name: 4.5 Assignment 4
  pageRef: /pages/trees/assignment-4/
  parent: 19c8cf92-e31d-034a-1ea1-5ad53194d892
  weight: 50
- identifier: 099087f8-28fe-0181-33bb-4d81b65985a1
  name: 5.1 Welcome to Unit 5
  pageRef: /pages/text-analytics/welcome-to-unit-5
  parent: 5847ad87-9afe-cf3e-9b93-c20cffe87acf
  weight: 10
- identifier: aea3bc9c-07f7-3648-65c4-6fec93dd8515
  name: '5.2 Turning Tweets into Knowledge: An Introduction to Text Analytics'
  pageRef: /pages/text-analytics/turning-tweets-into-knowledge-an-introduction-to-text-analytics/
  parent: 5847ad87-9afe-cf3e-9b93-c20cffe87acf
  weight: 20
- identifier: 0c9bd7c2-6f88-e1f3-72bb-45bfb1705096
  name: '5.3 Man vs. Machine: How IBM Built a Jeopardy Champion '
  pageRef: /pages/text-analytics/man-vs-machine-how-ibm-built-a-jeopardy-champion/
  parent: 5847ad87-9afe-cf3e-9b93-c20cffe87acf
  weight: 30
- identifier: d4b1a3b9-42ed-98d1-94fe-b3777ba22595
  name: '5.4 Predictive Coding: Bringing Text Analytics to the Courtroom  (Recitation)'
  pageRef: /pages/text-analytics/predictive-coding-bringing-text-analytics-to-the-courtroom-recitation/
  parent: 5847ad87-9afe-cf3e-9b93-c20cffe87acf
  weight: 40
- identifier: 81eae0fd-28f2-8733-6b79-2210ba33dfbb
  name: 5.5 Assignment 5
  pageRef: /pages/text-analytics/assignment-5/
  parent: 5847ad87-9afe-cf3e-9b93-c20cffe87acf
  weight: 50
- identifier: 33fa178e-64d4-cd25-dd86-7bb0db6ee3a5
  name: 6.1 Welcome to Unit 6
  pageRef: /pages/clustering/welcome-to-unit-6
  parent: 6e343503-94a0-f948-51f4-8f324b5f657f
  weight: 10
- identifier: b091b1be-c85a-85e0-60a8-3b7905c9dcce
  name: '6.2 Recommendations Worth a Million: An Introduction to Clustering '
  pageRef: /pages/clustering/recommendations-worth-a-million-an-introduction-to-clustering/
  parent: 6e343503-94a0-f948-51f4-8f324b5f657f
  weight: 20
- identifier: 0943bd81-1d9c-af9e-92bf-3c7bf9d7b9f2
  name: '6.3 Predictive Diagnosis: Discovering Patterns for Disease Detection '
  pageRef: /pages/clustering/predictive-diagnosis-discovering-patterns-for-disease-detection/
  parent: 6e343503-94a0-f948-51f4-8f324b5f657f
  weight: 30
- identifier: c6d206cc-fb15-28f6-048f-29e817450da7
  name: '6.4 Seeing the Big Picture: Segmenting Images to Create Data  (Recitation)'
  pageRef: /pages/clustering/seeing-the-big-picture-segmenting-images-to-create-data-recitation/
  parent: 6e343503-94a0-f948-51f4-8f324b5f657f
  weight: 40
- identifier: 940f7353-62c6-3a66-1b04-174a40036c29
  name: 6.5 Assignment 6
  pageRef: /pages/clustering/assignment-6
  parent: 6e343503-94a0-f948-51f4-8f324b5f657f
  weight: 50
- identifier: 252f83b9-1a54-bc0d-b02e-8b2cdb45007c
  name: 7.1 Welcome to Unit 7
  pageRef: /pages/visualization/welcome-to-unit-7
  parent: ab87d151-cf8c-fe95-c873-e816df164d38
  weight: 10
- identifier: 274ac6b9-daf6-cd65-874e-c643ab327953
  name: '7.2 Visualizing the World: An Introduction to Visualization'
  pageRef: /pages/visualization/visualizing-the-world-an-introduction-to-visualization/
  parent: ab87d151-cf8c-fe95-c873-e816df164d38
  weight: 20
- identifier: 716f78f6-1fe6-c5f4-7370-d7a3c4127827
  name: '7.3 The Analytical Policeman: Visualization for Law and Order'
  pageRef: /pages/visualization/the-analytical-policeman-visualization-for-law-and-order/
  parent: ab87d151-cf8c-fe95-c873-e816df164d38
  weight: 30
- identifier: 0af39afb-aff0-a226-a397-da1206ecd712
  name: '7.4 The Good, the Bad, and the Ugly: Visualization Recitation  (Recitation)'
  pageRef: /pages/visualization/the-good-the-bad-and-the-ugly-visualization-recitation-recitation/
  parent: ab87d151-cf8c-fe95-c873-e816df164d38
  weight: 40
- identifier: 056c6914-368d-638a-59e4-cebbc43acfe5
  name: 7.5 Assignment 7
  pageRef: /pages/visualization/assignment-7
  parent: ab87d151-cf8c-fe95-c873-e816df164d38
  weight: 50
- identifier: 006d219b-4918-0234-3c9c-2e5dce950c20
  name: 8.1 Welcome to Unit 8
  pageRef: /pages/linear-optimization/welcome-to-unit-8/
  parent: daafaa58-867c-9765-f1c4-c60a9c0ed426
  weight: 10
- identifier: 2900efa7-1aff-756d-feba-74c6d16f2d3d
  name: '8.2 Airline Revenue Management: An Introduction to Linear Optimization '
  pageRef: /pages/linear-optimization/airline-revenue-management-an-introduction-to-linear-optimization/
  parent: daafaa58-867c-9765-f1c4-c60a9c0ed426
  weight: 20
- identifier: 7a59278a-134c-5085-244c-381fc6090890
  name: '8.3 Radiation Therapy: An Application of Linear Optimization '
  pageRef: /pages/linear-optimization/radiation-therapy-an-application-of-linear-optimization/
  parent: daafaa58-867c-9765-f1c4-c60a9c0ed426
  weight: 30
- identifier: 696dd6e4-42cc-1fc4-7c9f-2924e2edfb26
  name: '8.4 Google AdWords: Optimizing Online Advertising  (Recitation)'
  pageRef: /pages/linear-optimization/google-adwords-optimizing-online-advertising-recitation/
  parent: daafaa58-867c-9765-f1c4-c60a9c0ed426
  weight: 40
- identifier: 6a5d4bdb-70f4-48f5-8697-82dbaa8537a8
  name: 8.5 Assignment 8
  pageRef: /pages/linear-optimization/assignment-8
  parent: daafaa58-867c-9765-f1c4-c60a9c0ed426
  weight: 50
- identifier: d99be1d9-3dd7-fc0a-70ba-351d93404d9c
  name: 9.1 Welcome to Unit 9
  pageRef: /pages/integer-optimization/welcome-to-unit-9
  parent: db42b40a-d705-f431-a7e2-3a1d11cec341
  weight: 10
- identifier: fbf2b704-9246-466e-f247-36bff248b7c3
  name: '9.2 Sports Scheduling: An Introduction to Integer Optimization '
  pageRef: /pages/integer-optimization/sports-scheduling-an-introduction-to-integer-optimization/
  parent: db42b40a-d705-f431-a7e2-3a1d11cec341
  weight: 20
- identifier: 11e612d8-9845-c6c9-6a73-07cebaa24191
  name: '9.3 eHarmony: Maximizing the Probability of Love '
  pageRef: /pages/integer-optimization/eharmony-maximizing-the-probability-of-love/
  parent: db42b40a-d705-f431-a7e2-3a1d11cec341
  weight: 30
- identifier: 1ebaa9f0-a112-c161-92d9-1227cd28b727
  name: '9.4 Operating Room Scheduling: Making Hospitals Run Smoothly  (Recitation)'
  pageRef: /pages/integer-optimization/operating-room-scheduling-making-hospitals-run-smoothly-recitation/
  parent: db42b40a-d705-f431-a7e2-3a1d11cec341
  weight: 40
- identifier: 2dbce7a6-bb37-17df-55b4-be0179616ad6
  name: 9.5 Assignment 9
  pageRef: /pages/integer-optimization/assignment-9/
  parent: db42b40a-d705-f431-a7e2-3a1d11cec341
  weight: 50
